[[ViennaRNA]]
arch = "aarch64"
git-tree-sha1 = "1a171a26d08a3fbc74feb900e0a1cb404ac74ab3"
os = "macos"

    [[ViennaRNA.download]]
    sha256 = "541f7602b981c79c0689dda44bca24cc2fb5163fa77b2e9def5023b19f4c14c5"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.4+0/ViennaRNA.v2.6.4.aarch64-apple-darwin.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "97b051f6672a6e339cd5d09ac05d1aa94d2a1252"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "e4b9a3e991bb08c59d325e3524212de2a3675f9acef9e653c641f3e237f7318c"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.4+0/ViennaRNA.v2.6.4.aarch64-linux-gnu-cxx03.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fc03fc21879e07c0e300f1e1ddb05ea9097a7c75"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "046b920bd29487b6418c7a0308ac216510f8834e6e8e50f4a335a0f253ac2173"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.4+0/ViennaRNA.v2.6.4.aarch64-linux-gnu-cxx11.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9bfabb87433db4fd34c143de3fd35a4e59b7cc9"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "14899233d6515983cbc22da1168deddca868ce4eba8a0f53454816a7dd0bf45a"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.4+0/ViennaRNA.v2.6.4.aarch64-linux-musl-cxx03.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72132d3c5d9a8a3bae0dfbd6aeb5182dabdffe05"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "0824aebf24e4a0674595f3a15a702647bf7a87b1b53597e51465e83f8a664117"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.4+0/ViennaRNA.v2.6.4.aarch64-linux-musl-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eb2d8794dc3156732502f6386c6913b63f791fb7"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "29dafcb1b7d4d55c714bf3cc34adb30a74cc51fe9e50294886b4f38970904102"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.4+0/ViennaRNA.v2.6.4.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85ca329b8f8f8a289645ce5d644268fe7754516e"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "2e876e4f2ec4254cf24440d6904aa6f8ed18df705989d05017a70e91a10cc83c"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.4+0/ViennaRNA.v2.6.4.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "78096f6f9779b45621a95fe8acea7388ddbe7d43"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "6a61d5db653ed7a535d31013e1e3b10c7e932860ca2bb877c5b69778371d9152"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.4+0/ViennaRNA.v2.6.4.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c924b1bf899c95daf7585b1035e3493d934870ce"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "de87ce1812374b68a6e04dd6e7a1d93e1261ac303a9cf9273066c323a061c6a1"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.4+0/ViennaRNA.v2.6.4.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a145550ae65086de6152adb102e232d5f6fefc8c"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "61b47a03c4271ae9dd51c419a6cb47fc8e1de21466a632dd72b9086268a71e38"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.4+0/ViennaRNA.v2.6.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f1d717f1839dd7c8ab483bb330c1b881d8f0015"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "eea2896d572474b9f985e636c6e5afda32ff86c83f36abffbbbd306e863df2e3"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.4+0/ViennaRNA.v2.6.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2a7837c1f48d395065b3f7f488c905a64ac51de0"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "8817e9b567a5848496c4ea26c23cbba7898774cb7b1e89902b1b0ddf5afbd908"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.4+0/ViennaRNA.v2.6.4.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b57cc695963e383d619606a632fdc5ba4f338d37"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "b6ccce2fdb2b98ac3477b3d2ccbc9a60d0c4c09ce10c8b35640561ce02f69895"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.4+0/ViennaRNA.v2.6.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fefc82a4a53cc3103ad25f1018599f95e3eeb8c0"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "c04f0664fc02f6e473df03d06cb2d74f2c3e0cbc13696be0831ca65f3fcfe45b"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.4+0/ViennaRNA.v2.6.4.i686-linux-gnu-cxx03.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a788f280c6d8b645543f241a1b4ef0e3dcb2400"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "86de86cdb7c4c75afda6a01ed12726699bd593e51700ce463567d178fc8bbe13"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.4+0/ViennaRNA.v2.6.4.i686-linux-gnu-cxx11.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4dad716093898b3698cd2d0817021580b3f48588"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "ed8a30f51e729eecd2a154fc77dcf331d19697ce22072b48e8a491c6cf56aa0b"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.4+0/ViennaRNA.v2.6.4.i686-linux-musl-cxx03.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c3b14554d6587a331c745a144e580aefb697112"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "d00ae98daa7091c3deb97dbef8e371f209cb29b014789c944d8bff9ed595a714"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.4+0/ViennaRNA.v2.6.4.i686-linux-musl-cxx11.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "30990eb7d7e49714d43e4ee07281983f462d5cb0"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "13b28994ad54835f958bd36a984170396f77ee35f706e28549cc19a38c75b061"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.4+0/ViennaRNA.v2.6.4.i686-w64-mingw32-cxx03.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48c8a3bc482f0288d130277130f7811bb9d8ae1f"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "87e54d8d3b9e93db4df8252e36656602398d01b15b6aa7bbdad3cf62e1b1e787"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.4+0/ViennaRNA.v2.6.4.i686-w64-mingw32-cxx11.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
git-tree-sha1 = "56f694ba7229440a444e4b75de73b3905e57301c"
os = "macos"

    [[ViennaRNA.download]]
    sha256 = "609880e25e31ffca08a025a304ef2ef9a164503675da3e252dc6fe63c553460a"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.4+0/ViennaRNA.v2.6.4.x86_64-apple-darwin.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "281d9b0724868248cb812b7794c142654651ffbb"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "804b3b463fb3f3508748a0fffea47f29cdaf596475255c69f83c75d591ddf915"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.4+0/ViennaRNA.v2.6.4.x86_64-linux-gnu-cxx03.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b994b3880dac7f5363549ae63fc6fccbc8890cf7"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "6c3fd6a5af9f9660212c75fcb9ec1b2cccf957ce1db5e9527d8c58b99c7bba25"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.4+0/ViennaRNA.v2.6.4.x86_64-linux-gnu-cxx11.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bb9aedc83ca9b9d568e5a9fa0ec898747cab319b"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "69904fc93d8a138cebbc203c244c15f20e48cadb0556ef6a37b940f7d77f95f3"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.4+0/ViennaRNA.v2.6.4.x86_64-linux-musl-cxx03.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5920667e33873725f9c3197935ecfb9a2d49e188"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "70626ed3bb0193b1eb7561f5d64fae866686987292744e25adb01f19d1339fce"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.4+0/ViennaRNA.v2.6.4.x86_64-linux-musl-cxx11.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
git-tree-sha1 = "25cbea4eed41898cd1126b53114f7de33be9efae"
os = "freebsd"

    [[ViennaRNA.download]]
    sha256 = "0eeaecbaf5b71b327caf637d0acac8aee85bb9b3e02935d4614bf32ac142e435"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.4+0/ViennaRNA.v2.6.4.x86_64-unknown-freebsd.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e5224eb81ae032daf4103dfa33b99ec39d03fa30"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "cce52886cc248d00f9ad0fb9c8d34abb5b0af3d73ddedf9ae8ba225c8e962681"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.4+0/ViennaRNA.v2.6.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e7e57fe10919915c52867a1bd08112e2607d95f"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "7c9c55fecf837f922e838851d54b947d4ed7de6a630541107ecdfd99487444e5"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.4+0/ViennaRNA.v2.6.4.x86_64-w64-mingw32-cxx11.tar.gz"
