[[ViennaRNA]]
arch = "aarch64"
git-tree-sha1 = "1fa669f56ae138c2d9771ea9dbb0bd012f1cb05e"
os = "macos"

    [[ViennaRNA.download]]
    sha256 = "ad4907592efcc7821387dc1888ade1e8456ba17e5601a45468011dbffa3a80f7"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.aarch64-apple-darwin.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a23cce323cde5b19299228fd399baa4a374f26d"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "bde5a35160d10993bd08b684da99c2202d8aeae0de1b466d4ea7bd66527f0b00"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.aarch64-linux-gnu-cxx03.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18ff8a3909eb06acf5bc4a51e856c52d606290c5"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "02410934caa1b2f419a3942f530878e38785a5b4c68598855b479d9372ab150f"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.aarch64-linux-gnu-cxx11.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "59c28c77054fa42fd5e17eb9ac93ca6dcebc649a"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "22c28b081832eb5f39a69c0dad139468bf9205e1b8c158309d80573b13ff48d7"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.aarch64-linux-musl-cxx03.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b846fae41462a1e09ccd919fb17342468b523dcc"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "f0d967b6387c509569802eda70337b2a9417bd423d4cbdee9122a42bba17c373"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.aarch64-linux-musl-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc2f67435996d68c3d3f6e3041f313a989cf4880"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "124b985a87737855235e1fc23d7814a35d7b9e2fd31f59c9feb43fbe568938b1"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c770b5cb2733acfcc985a8ca55c04fa48ed355c3"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "3ded3355186063b3af969c581e1393c928bef0930c47a9faeb91efc4a4d0228e"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cf6043ab6cf0908fc70d20723bea25d3d0b2eb5b"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "621eea176f347015f2457742d6b1a838540e2338c958f009e153060439e32852"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cf40bdca80be1eb8224779dc69f3e3b39ccfdce1"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "501c629cebbbb77d2f885a08347d28154792a1f30cee502a64b4769e7160629a"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "189c419c17bfa27348c9a646c59e078c2e33f431"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "a02ab7a353d1d3fb164ba72e31c8305d6c265836a563d5839de9e6d0ce2759d3"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c345f07cc8f97c5abbbf0197a54dce20b48184c"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "c6f1e05bc83b1b76f8da42154fd74037b7138a1e823d17cac29b240224e25092"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0a42efbddbe672401a2117d3b4aa24c4166c4248"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "02e88f1901badbd5b470097e7bcad7c9d564934afa82f6032dff48193bef0ecd"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7776ae28c5eab2bec46dff1ff934f9a071643136"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "d0bd8b15757972d9c5c133d89b0dcf9a175ec47f1c47616a8f7bc943ddb082dc"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c5e5e9bb1e280d055f72999de1794767563e9a9c"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "db3ecb1d1820acd16b9d3f09eab796537638081c959c3cfefe6446dde1c417d1"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.i686-linux-gnu-cxx03.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2ae7396b45f3c49460b93e69067f37d77328bf8"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "0ec1ed8d6e6a3fc647ff146243e3b1fc36901412d848e50b6142efacc40a9460"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.i686-linux-gnu-cxx11.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a3a1aa50a31dae3a888d0badd79ac63c5f5f60c9"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "44d1cd8013a999a2d8bee6d33b18a3a9564350b36350c5e039b59c8cd6c95dab"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.i686-linux-musl-cxx03.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "046873fd01e4ce7ed28e8def661fc8d786e7dea2"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "d5e76efb8f28412fd95924aa4d85db89d5d9f1e255ccf56b4f8c30c5d0bd6c49"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.i686-linux-musl-cxx11.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f935bfdfa76748c57da8509fcca5824db892d7a3"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "095ad76c314d7df4af7ebd66d622cad1da1df1e36a51bd611f3b44fd8dcd6a2e"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.i686-w64-mingw32-cxx03.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "42f7a4c751a6b3b65cc3404687442ce39df59a60"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "05b7bf5a267c7ee7e335e4a3ad558cd2e4938eacec8adf4ee7229e612c5c62fb"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.i686-w64-mingw32-cxx11.tar.gz"
[[ViennaRNA]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e7281a4678a211202cfbce329ffd925050987e5b"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "20ad72a27eb32a5ea049e7a601c222dc20e4b2f29f1fb0d2ddf74d29dd39ecd6"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ViennaRNA]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2d93925dd64a459045648458e29da612d40b6e0"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "85d9963f6d43aa472195d0aad498c154381f1e6a8da0243f998e4dd398564502"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
git-tree-sha1 = "7600a121663fc2e0abbcd087b310c0cdaf178e8c"
os = "macos"

    [[ViennaRNA.download]]
    sha256 = "04f0a80a2c28f5eda38a2f924ac0e4309c0f002305671d1eac0897b632bb9477"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.x86_64-apple-darwin.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ca8e87b4dd0c7a391890c855ddbab0d4757273d9"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "9bf99aec5713437e4120dd6e6c2ebdc9a71f7689b6b18934974eb3f5c64bc0d9"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.x86_64-linux-gnu-cxx03.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d35ae1de644ffd851027bea7ee94806672c13ea1"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "d3f7a1a2e0dfe51d241aea2d8b716e19daa9cf412d156d6326a0d9e439d5eb64"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.x86_64-linux-gnu-cxx11.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f3bfacc2b31d45eab96ca14afc5a24017fca4aec"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "89a829ebaa19811abd92ae5467887108f9f091e2ff4d3b1f508d71c11c496d68"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.x86_64-linux-musl-cxx03.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "723e3c36cc1faa8e15c074b48a625d4f1029c853"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "ade95e39f38e85186983500fd862de26e96e32eb7846119d56920b8e2ab83657"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.x86_64-linux-musl-cxx11.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
git-tree-sha1 = "1fd56d973ee9308afd6cb50b44ed6cd40520b67e"
os = "freebsd"

    [[ViennaRNA.download]]
    sha256 = "2cca4b213ccc2057f572b527b01396955fafbce6bffca5adac04d1fd82b72fe8"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.x86_64-unknown-freebsd.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "44ed3a0f78572d4fcf3287cd7a83ed97518d4026"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "12bcf18959cb156f7d577e19bb9f6e99d0277b7ccff9d3b6e44a9707b2e9cfe0"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.x86_64-w64-mingw32-cxx03.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1661b045cab92c258fed4cbe361714a64cd50701"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "d75b6eb957fbfa1a6a956cd4623b090b5221f36103face9fdeff23f3fa3b8388"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.4.18+1/ViennaRNA.v2.4.18.x86_64-w64-mingw32-cxx11.tar.gz"
