[[ViennaRNA]]
arch = "aarch64"
git-tree-sha1 = "749869f3a7bb563fec06fb0183e1eb9ab33fed6b"
os = "macos"

    [[ViennaRNA.download]]
    sha256 = "29567bae1558ae543e7106ae2668f9ae29bc6b6996ea8d23caf67cb8bbe6bd15"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v1.8.5+0/ViennaRNA.v1.8.5.aarch64-apple-darwin.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
git-tree-sha1 = "40adfee72ead040b2f514976f17030630a17d802"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "9cadd4a26902cdcdbc8b16efb2afcdf0728f15b01a80c6b463863eaf659ed6a1"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v1.8.5+0/ViennaRNA.v1.8.5.aarch64-linux-gnu.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
git-tree-sha1 = "eb4bc398d6a4a1d7c87cf063b5e0953197420950"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "f1926f2661af2805615a249e4a5aecc13f11d6d3f0d56ae65da629da7a76e13e"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v1.8.5+0/ViennaRNA.v1.8.5.aarch64-linux-musl.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3a6753a98dd77200e3a66741daa490a309a5dbe2"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "e837537b956e4159a961ff0ce0f69ed837dad91d93ed47e03d770529f4a2a61b"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v1.8.5+0/ViennaRNA.v1.8.5.armv6l-linux-gnueabihf.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "00cb84f2ed230abd1c7b1ab3ea3f77b849949931"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "7e329bad985e21ef94acad5b27803dc98f88642c01f7a1f2c0cef4347b2265db"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v1.8.5+0/ViennaRNA.v1.8.5.armv6l-linux-musleabihf.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5758464479a7a5bb6f9da643d6e28ff839152c24"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "a418daedf4d4ddcdfc76c8ac2f4c579e3a7d1048770653cad71eadd6f1881b44"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v1.8.5+0/ViennaRNA.v1.8.5.armv7l-linux-gnueabihf.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "487b889dc3820c1f3729d157894e84282dcdba33"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "803e299c10e9773c194012258d35c1f09cecc86d266bd318b2f6c6e168a24605"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v1.8.5+0/ViennaRNA.v1.8.5.armv7l-linux-musleabihf.tar.gz"
[[ViennaRNA]]
arch = "i686"
git-tree-sha1 = "62c647e7263e566907abfa2f8911ff8839b51936"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "c65579f6d3fe1e3434b09344c59629512137436174f52c2c84fee530a2017a79"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v1.8.5+0/ViennaRNA.v1.8.5.i686-linux-gnu.tar.gz"
[[ViennaRNA]]
arch = "i686"
git-tree-sha1 = "11882a68a399b35b15362dafc3a642b4ce908aaa"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "992e3978f54a2a336579a8aea96fb18722a28e6831c9ec9752eebb0840caee4a"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v1.8.5+0/ViennaRNA.v1.8.5.i686-linux-musl.tar.gz"
[[ViennaRNA]]
arch = "i686"
git-tree-sha1 = "f6f08cb7aabe120987ff77e6bdc65ed402df17a4"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "dfb31b17be52a77c7284173a45360b956eb11df62f3b6059b6f62fd3b8fa4e78"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v1.8.5+0/ViennaRNA.v1.8.5.i686-w64-mingw32.tar.gz"
[[ViennaRNA]]
arch = "powerpc64le"
git-tree-sha1 = "69d9f1ed7028df2a5deec0a31848904e93d470af"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "7c5ebe0806ca1de2f86862b9aad010efe9741bf65c5c2ae51654bc1ad3a66dcf"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v1.8.5+0/ViennaRNA.v1.8.5.powerpc64le-linux-gnu.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
git-tree-sha1 = "83af30bf9eebfdbe459942a30cc7901a65d6269b"
os = "macos"

    [[ViennaRNA.download]]
    sha256 = "1a1d764931ca84c54ff5b2267a4af8ef8b62b1801862d0392f07ac666edd58bd"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v1.8.5+0/ViennaRNA.v1.8.5.x86_64-apple-darwin.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
git-tree-sha1 = "a82f0cded01e54a9606e76680df0f64aee5e9750"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "c29adc9e8a59825ebdb03be31f09a75f65e82a2378a51433a381561e2d905cc3"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v1.8.5+0/ViennaRNA.v1.8.5.x86_64-linux-gnu.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
git-tree-sha1 = "72c6dd5a81250d1fb615830236d8bcfcdebdaaf0"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "b3ef8e568251d9c8c6ac4e85b980b7cb7fe6a66b419ab3fa513843f95324ee84"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v1.8.5+0/ViennaRNA.v1.8.5.x86_64-linux-musl.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
git-tree-sha1 = "11d23bd3f165749dde224eb31d316c735c9a4a77"
os = "freebsd"

    [[ViennaRNA.download]]
    sha256 = "b5c8b0a9ba6b27988ec9878cf4008562519461099b7eec1f9b2bf9fea65fb82b"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v1.8.5+0/ViennaRNA.v1.8.5.x86_64-unknown-freebsd.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
git-tree-sha1 = "19324eb2051d92052df0c57397819a955316bece"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "d3444821ce95d7f728b0bc8a6f7341655c55ab3628c35a8a486d11c1c52f680e"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v1.8.5+0/ViennaRNA.v1.8.5.x86_64-w64-mingw32.tar.gz"
