[[ViennaRNA]]
arch = "aarch64"
git-tree-sha1 = "8cae1e5444f8b0d5fdc67fcc834fa5ad18e5fb00"
os = "macos"

    [[ViennaRNA.download]]
    sha256 = "18dc0663a4cecd147422803055a5aa642d24974d91716fa22726eef8f4e5e52e"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+1/ViennaRNA.v2.5.1.aarch64-apple-darwin.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "68d540af0953f261e55496e61397c5466743962b"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "10cd218fd0b382cf0a765accefbd8803651f64cc9cfdbf1843bd5e9e2e916033"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+1/ViennaRNA.v2.5.1.aarch64-linux-gnu-cxx03.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a17af6f381b8e7af8d30c88fa388e9c5c83c54d9"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "4cb888adab63f4b9d87352fb1829eb2ee404d1c9a6be50da8d7708443413a8fe"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+1/ViennaRNA.v2.5.1.aarch64-linux-gnu-cxx11.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2ffabcf10617d541d0375b081b29360ab1fd0fa3"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "31b5ff194fb19a345a21eb2d60f358002f184cd60a2f586583a4a9a93162f6dc"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+1/ViennaRNA.v2.5.1.aarch64-linux-musl-cxx03.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d40f2d130919c0361d7af32e8ac935f4399f8b48"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "67bed122651abcc2b504bcbca5926ef7bb1653ec829840edff15590648fa3d9f"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+1/ViennaRNA.v2.5.1.aarch64-linux-musl-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7a1b0a8885744accca40e7855a775d0c06022595"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "77e161544484445d0c3f2ea3ca59153f9f5f69e4d8e6a0ad20ca0ec8c832c46f"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+1/ViennaRNA.v2.5.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3cc3efda200b73f8d6259f90f8a6b1322b465e2c"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "5b233319aaf833685649305c62d8396bea2dd24264d26723954eabd8832e28be"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+1/ViennaRNA.v2.5.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3337262f872c6fbb88bf20cb42da973313cf0795"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "5a6f438a386da021008e775f7d530054abbbbb5e0e79f5791ed8aa0f87acba91"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+1/ViennaRNA.v2.5.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f5a8bf063377812870f22b8ef5c47c022346f6ba"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "bc63ae66ffe5777f10c646e4e2696e22b86ce5db56d0f8ca8482c01053b8610a"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+1/ViennaRNA.v2.5.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b2d053a6914cbf83177f7c81c8ccc7aa979ce4d3"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "5ef7b83abf3997258d0321b9999011bc1a7e9ddc8a4732ef4461ea1bdd3645dc"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+1/ViennaRNA.v2.5.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ced4f8418b1b89d1ad815822a28fa1211f54eae"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "cd8dc97d9000b74247f6e1608a9a42b4ee13eca904e5d73ed52ea677c4b8746a"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+1/ViennaRNA.v2.5.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "15db856cb609d5b2fb13be64094c355ba234cc30"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "4181a0ea4aff4025f742270125b172705f9164932df5e683d2ee7444d72903a3"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+1/ViennaRNA.v2.5.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f55922bcee56a45ada2178cbb485bed15f348ce"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "690f24ff66dfb2614146014cd9566d422141ecbfada82d25fd14e8d88ec2c8ce"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+1/ViennaRNA.v2.5.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f58e28f493e911c26aeff940b98342b53f00c452"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "249e12a89872511a0e8c7bb23d546161b10a9237b38bf633e4d163564743fa6f"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+1/ViennaRNA.v2.5.1.i686-linux-gnu-cxx03.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc40517fe066cf8f57b51dd4d2b094148c94deef"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "96ce99bb5f319f949d6b67373d024b5155c56e1a682222cb313574f93771ea0d"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+1/ViennaRNA.v2.5.1.i686-linux-gnu-cxx11.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c80104769209fbdcb9ce740967f29bdb85afd1b0"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "da67c4140ac09b5c3571e8c49cadf9b709f458fb9ab52a5037468a28742e1be6"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+1/ViennaRNA.v2.5.1.i686-linux-musl-cxx03.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2106d06cc87a2f583c64d6e1b8fb19208debcff7"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "9682ca3b3681ff58909ad695e54180be039c7694039d13934f8a729eb832eae2"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+1/ViennaRNA.v2.5.1.i686-linux-musl-cxx11.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "35f12fdc8959988d47bc90c2ae0f3a96c297d252"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "bd0fa2a9892a89720df89ede462959d1f1e98e27b321171a901da2a3305b10fd"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+1/ViennaRNA.v2.5.1.i686-w64-mingw32-cxx03.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e055c4973caeb04bd955a998e175001a23c4379b"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "640abd4954dc7745331e6b506516683ce22361657c64b5e9cacf739e801c86cd"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+1/ViennaRNA.v2.5.1.i686-w64-mingw32-cxx11.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
git-tree-sha1 = "0e605c1d324346c9f5a0cf89df1f8dce20eda0d6"
os = "macos"

    [[ViennaRNA.download]]
    sha256 = "c1fc6b664cfa0b3613a7bc43befea6e77390ef081b2fe8803ff4ede963d4791b"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+1/ViennaRNA.v2.5.1.x86_64-apple-darwin.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3518eb779d386c7d69faf1f8184ebf7542bb7918"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "ce7fc43145d91397aef1c0b776eb354b424f3d5a7d828e55f8b222549c9cf8f8"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+1/ViennaRNA.v2.5.1.x86_64-linux-gnu-cxx03.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d18c3ca9c093461643fbd7ac3e9758fbd9bd9221"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "25940e25f5552ecae34ab832da7dd4238dd8a022d4977b1700a59af3fae599bd"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+1/ViennaRNA.v2.5.1.x86_64-linux-gnu-cxx11.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b239da1af3ffc8810329913401fa5c68b5df45f6"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "3a43289458e165841d44ae20e347f046a6110c910a53013562ec2a52ee4479c9"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+1/ViennaRNA.v2.5.1.x86_64-linux-musl-cxx03.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1c54ef2d4a75b9e9361f17a6e3cd8a4caeff231"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "06b9b7e5b7e403216862c44fedb7564d971928f562b17bd56965d58794bfaaaa"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+1/ViennaRNA.v2.5.1.x86_64-linux-musl-cxx11.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
git-tree-sha1 = "4f6b532df912416b95ab13e5ac264e59c8225bbc"
os = "freebsd"

    [[ViennaRNA.download]]
    sha256 = "bb372822fb150b252a888f098ebdde20b4d1c29bc697a23d452f4b45dcec94d1"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+1/ViennaRNA.v2.5.1.x86_64-unknown-freebsd.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8e278e135e1e31b9d173230d08e9b099a1c9a2bd"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "a404df8f06c3329997677b15aa47df4cfa897d9ff0386fe7d7f3c5c15b78b819"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+1/ViennaRNA.v2.5.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1973057eb1ed15b44da0057b37b2783e0eb68570"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "49f540874cc02465f0dc34a340960de6ffe1f03b478f241696018be5782c8c17"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+1/ViennaRNA.v2.5.1.x86_64-w64-mingw32-cxx11.tar.gz"
