[[ViennaRNA]]
arch = "aarch64"
git-tree-sha1 = "44ebbe0863c5de36bf39133ff76a74494d22eb3b"
os = "macos"

    [[ViennaRNA.download]]
    sha256 = "8fd6195a9139392b0d5ea92a07992e5338a0eca21c04f693b185a42489af262d"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.3+0/ViennaRNA.v2.6.3.aarch64-apple-darwin.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9e7f1efa083ab725ec71f7557f5edf19c3571207"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "dbedcf15337bdcb98fae552a6a6ff9b36fda2b35a7f887c4f0a06471dc626fbe"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.3+0/ViennaRNA.v2.6.3.aarch64-linux-gnu-cxx03.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df1f03ec23bb6c243f834943f3efe1343d1706e6"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "219e6b678f977fac906ff7cd01ef1cc79ec9e71fde720f5eb40110f34afa1f6c"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.3+0/ViennaRNA.v2.6.3.aarch64-linux-gnu-cxx11.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eae95035a483715812d89c042230010d1b44255a"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "e64f2d0cae65482a39783ea59d2e2a5d67bc182b72805267ff70917ae9e808fe"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.3+0/ViennaRNA.v2.6.3.aarch64-linux-musl-cxx03.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e4bfadb9fb3a41dd12ab95bbb2700f36a661746b"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "a8e775e40b8332663d3b572836201fb19b8f4051cd87a7d8ec2ad8f42fb3f2ac"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.3+0/ViennaRNA.v2.6.3.aarch64-linux-musl-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a0a643f0de43c1f5ab3eeac3b1da30e1465083a4"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "75377cf2ed03ec4f5993b62313dc0ed3aae278acc74208f440cbc573a6150b3e"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.3+0/ViennaRNA.v2.6.3.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6deb3917bbaf9c88b385c35c9fa0cf2e246cf8d0"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "a6e9601f5dcb3cbb4e3994959855ac85258c9891d1ae92c10c8fda1c23a0bdfe"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.3+0/ViennaRNA.v2.6.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9386953e42ca31cb80bb5f0f75ae520257049f05"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "e657404791f4e46e7e34006e1761772c31a3e8eab0e9defbb06e52b705fe82ba"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.3+0/ViennaRNA.v2.6.3.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "072e813f9a9b8e79109286a15062597c27e99302"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "59d9872dfc1d9b514685cbffc1815fffe432843a8d5e679b90f16305e2cfe1a3"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.3+0/ViennaRNA.v2.6.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d65c2e28db1639e75edec24396037c844eb1b83"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "2b1d86623288774e274b603cefa9ef6772d35b5ce13668ca774aaf250e1f6489"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.3+0/ViennaRNA.v2.6.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f90bc8eb717404226adf8d01eac54e4a37051b53"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "06bec26d7a30fa2efa66e19eaf21514403848832042db55d08a728185bb569b1"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.3+0/ViennaRNA.v2.6.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2f4c592de2b14a8745248e934c1518848ec40dfa"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "1400e14e75f23fd36869060950d02c24905989474aa335231c4c7f188b71d9cb"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.3+0/ViennaRNA.v2.6.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "92b020e85cc12597e7888d13f9cbdc5014eb22d5"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "0587d614a891587fa20ad3e4180d81defce65cc600b8ad1a5addc3d1364ed4a1"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.3+0/ViennaRNA.v2.6.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "45def3333fe880d6ada7377dfb1955220f5c3f91"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "88a0aca3ea24b1e46ecd8cf1c6211a55ae11cf0bfaaafb58d730d4aa5c9d82b2"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.3+0/ViennaRNA.v2.6.3.i686-linux-gnu-cxx03.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "40a1df6baa96091c0f2a58eb844bec392d3a236f"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "05ce273bd2dcb924160ffbf484aa0a8065c5f7558b2e06df263c2277b9326362"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.3+0/ViennaRNA.v2.6.3.i686-linux-gnu-cxx11.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "335715a650927be21683aafa6ec72a9477502ffd"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "c4cedaf401e510d2cfa3f13d52c60227dd1ce3307cfce56d3196a98588337a04"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.3+0/ViennaRNA.v2.6.3.i686-linux-musl-cxx03.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3df3a4358d36ab1dfde9dbea53ae04b2b7d8c980"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "fc8c9d4cb26c439ce12b95e23214ae3efda6d6173a5d8d1f1a53ba7a2a63fc6a"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.3+0/ViennaRNA.v2.6.3.i686-linux-musl-cxx11.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "23738cbf419a3e65a6d9e8b50ec8c5417b99ae61"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "3a03d23699c7c09df29686338a7351c75726c8f1498913555948444e7e007c8d"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.3+0/ViennaRNA.v2.6.3.i686-w64-mingw32-cxx03.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ab88119d1d57b92baf624bb9b3120b6247e585b7"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "3cb52a6e51b5174cd2b92c92d66a038c99a5862869093a991c0d8cff2660f373"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.3+0/ViennaRNA.v2.6.3.i686-w64-mingw32-cxx11.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
git-tree-sha1 = "fb5dc57a20edb0ee9913150c61411a26e164640b"
os = "macos"

    [[ViennaRNA.download]]
    sha256 = "88b0f1d6c310e48e6c15ab68ab263915ec56a61936ad337c84f8748b218f8d2e"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.3+0/ViennaRNA.v2.6.3.x86_64-apple-darwin.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b02de2655b3ff36eb9b402a5f13b8793559570c6"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "c712394630a3c92238a91945ede27a2942d6bd6e3033dbe3a787b442ac49a2b6"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.3+0/ViennaRNA.v2.6.3.x86_64-linux-gnu-cxx03.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "76a8380c6cc60b7486c1970ddaba5a838f255b46"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "23d25dfea3774a97715f1c4889b4c6facef2dcdb1af76d3f3a80c985401f86bc"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.3+0/ViennaRNA.v2.6.3.x86_64-linux-gnu-cxx11.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5367c4ec418e3d7d20b50f2f65ad9cb24f832b07"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "8be894e521727b0c014872d99446e16037a0561050627f3ddec9b40595e73ef9"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.3+0/ViennaRNA.v2.6.3.x86_64-linux-musl-cxx03.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9db6f42fa9b501521b0717be6dc74fd03924f902"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "5d795afb96f263ab38fac5b17acd98353e99421059630d4782a7c5334e4d9d07"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.3+0/ViennaRNA.v2.6.3.x86_64-linux-musl-cxx11.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
git-tree-sha1 = "6f7462854d0b9e7e199cbd414f494c07b2073822"
os = "freebsd"

    [[ViennaRNA.download]]
    sha256 = "f23d075d3dab576585a14baa5e4107e6d7cdf7d8c7a9cf092528a0b517195883"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.3+0/ViennaRNA.v2.6.3.x86_64-unknown-freebsd.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef0540169810507efb3a77ea3a5885143fe92463"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "5b1a62589c9661983f9f6c432bc80d3ca368f581dc76d684fd4bfbe42b95cc3d"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.3+0/ViennaRNA.v2.6.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64e48c99989dd30e8d6e7f2d76e6e7dedc92fded"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "a232a7424c03aa2dabee5b10c14ec65df26800bf053fceace39a073a3e4fc00b"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.3+0/ViennaRNA.v2.6.3.x86_64-w64-mingw32-cxx11.tar.gz"
