[[ViennaRNA]]
arch = "aarch64"
git-tree-sha1 = "43148176287aad3005232a390d8c0ea282ff0330"
os = "macos"

    [[ViennaRNA.download]]
    sha256 = "0875eaa6b8705f1abad69d848296c0f2c6f1f94ff966d150ef95abf890d0facb"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.0+0/ViennaRNA.v2.5.0.aarch64-apple-darwin.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e77f7edaf8bef296605b291c820482521ded185e"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "b1a6bbce8b0727c33cc0dfde2fa69cc4ca9908831f630a8be47b44df84e1ef56"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.0+0/ViennaRNA.v2.5.0.aarch64-linux-gnu-cxx03.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa1c9dbc7041f5a9d5e3e5569bbb33db740338fc"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "989d545b39a1427e9b1553df8f5b873c5e3a82fa6c7ad3cd59a7a475c55d632e"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.0+0/ViennaRNA.v2.5.0.aarch64-linux-gnu-cxx11.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "086189b6dfd9ef5d925327badf84e707f524edb4"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "ae0c742aa36303bb5e53968e9917f7871a49af951581db175622d3f5a952ed98"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.0+0/ViennaRNA.v2.5.0.aarch64-linux-musl-cxx03.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e11d42904e9884eb31ebf49ef52809be3e87eeef"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "a37b9e2e751c240dfe83d2ad1c829a59b38a2d2bc48abf989e406925f6dbbfef"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.0+0/ViennaRNA.v2.5.0.aarch64-linux-musl-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2e0f129b4427a7b4883160a867eb397f6d04f3a3"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "98ec8abda85eb7903d99400e60b9737200d722f60817030903d63beb9f244341"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.0+0/ViennaRNA.v2.5.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "823afc9ce2d5fdb1592542d12a66f66e3e61cf23"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "1b0dfbf04827fcf44205c1b09099efdb1bdaa50194de50cc6ed9ca1a9d2a5c87"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.0+0/ViennaRNA.v2.5.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c66821c5fb9c091cf4ed09d8dd0955bdcb64ee30"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "d2d76de706ef1f4481b9cd2dd2ab1cb5887d9ee3bc4aa3e7ebe797cd6c30298d"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.0+0/ViennaRNA.v2.5.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db4fef53507cec4f766d9ea06954b20873d31c41"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "8665995e03e70e9a69ce5c0d5c464a166492540b4ad8006aa403738478227716"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.0+0/ViennaRNA.v2.5.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4aec443454db55fec5c444dc9825c9e4a89b3f41"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "4c06b883c24833fc9e455bec3a1e978a9e3945939d459cbd7c5e83489cb1a757"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.0+0/ViennaRNA.v2.5.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "46b53a97d02673d9affef266c204d9369a87a597"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "8dc5932bd320c5e2bb5af89d496e1976b0eb38b352a194c3ceaa25f2aecdd1a3"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.0+0/ViennaRNA.v2.5.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "87326a31a6f981e7d5dd8101a7fc9061268ec7e6"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "6de1b1ed98f261b06df2ee37ea6534a68dddf4ed380852a649f671d765584e23"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.0+0/ViennaRNA.v2.5.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7838b8288d4265713b0c59ce7d78d05fe47dbd4"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "a961d0af4a46d8b74f427836d3b32ff93620cc395a0b1c972f80e9cfa1a26942"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.0+0/ViennaRNA.v2.5.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef3b0436815aeddfa992b4738ebf8eba85f1df92"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "41216311801fa2cf0f73767fa228d76c512d6836d4d73653ff0bfa4b813d17b2"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.0+0/ViennaRNA.v2.5.0.i686-linux-gnu-cxx03.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56c6a420d5063d748050732df80ccd7faee6d692"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "7db71fbf20492ce81bc02d1739e4818a2cfd3ffe99d4fdd7986f39807b6227ce"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.0+0/ViennaRNA.v2.5.0.i686-linux-gnu-cxx11.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3b316a5480161202c35f7423191c5511dd1d34a4"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "c0431ce8f2548b1a169a00e2214f12002ebf75f3b2e8dd666c53d89911e70a4c"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.0+0/ViennaRNA.v2.5.0.i686-linux-musl-cxx03.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bea508d63d427d1e7dd3dda51de517e099e2ce5a"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "58ce658c2edf5fb14df8272b4004e4e32368c5ef5833c11e8160bfaeac025edf"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.0+0/ViennaRNA.v2.5.0.i686-linux-musl-cxx11.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "074c8906746a93da20f1f39e73b9a49ec6cce37b"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "2abb16b8d55517d5cad7d9f08e69f10f29fb73bf565e3712e0f981a322297d0e"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.0+0/ViennaRNA.v2.5.0.i686-w64-mingw32-cxx03.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09416d49c64b1632053603e70ecf0deeab75c55f"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "9cc612caabfe4a02ddc501ca656cbcb12f1574dec096fdefe1e44c4264f1cffb"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.0+0/ViennaRNA.v2.5.0.i686-w64-mingw32-cxx11.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
git-tree-sha1 = "34435562b115d771ffe0c4a0d01a7b8c8e2da864"
os = "macos"

    [[ViennaRNA.download]]
    sha256 = "141bc048908937b6a9db7166e7ab5161077db08899f8ec68e23e91db1ffb8694"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.0+0/ViennaRNA.v2.5.0.x86_64-apple-darwin.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "91a54484d2085b66b5c8797eeeabd5c397a55f16"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "b5b49d53ead4f62d1ef235516a47ccf41d7fc821ccf56c9d59654e2103737b8c"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.0+0/ViennaRNA.v2.5.0.x86_64-linux-gnu-cxx03.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "725e603448ac6c44bfbbf2df16f3225673d1ff38"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "3da0162459e57d19f49f935ab086c3941c6298fe5636faf0441f8ce8a7f8d174"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.0+0/ViennaRNA.v2.5.0.x86_64-linux-gnu-cxx11.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f3f3e42e2877ad6e19bf45df4d26a16af94a58ca"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "4c0d3aae8e98677e478fe1b82d3a7d367ca83a94c4c3c493fac5471a87a83c65"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.0+0/ViennaRNA.v2.5.0.x86_64-linux-musl-cxx03.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d2cc1b12b3e276d605122793560eaa138b8ee9d"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "c0425eb00680cb4ecb9bd99f18ca4f8e8b7690d09fbc0c98ff72f6b839b76d35"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.0+0/ViennaRNA.v2.5.0.x86_64-linux-musl-cxx11.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
git-tree-sha1 = "ed9bdf750e11d26b47d0c63d77cc8863eb95992e"
os = "freebsd"

    [[ViennaRNA.download]]
    sha256 = "45197e41b7fe01bc1ddb06a4c6fe8ca3ee9ac77d6fe7cf90af6cbc7cd981f403"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.0+0/ViennaRNA.v2.5.0.x86_64-unknown-freebsd.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "348340b041da6d5b1d27a92a54343a32f3baf19c"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "8a84c914300b3f458211d6545afacc41033ff18025780e476c14aaba54cbb2f8"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.0+0/ViennaRNA.v2.5.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df30990a199873c06f80709077970ec2a9f8a27d"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "63d91b864968e8ffe4df09c19f1a7be727a9d30f08bdbb4fa45f61ae9ba3cb07"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.0+0/ViennaRNA.v2.5.0.x86_64-w64-mingw32-cxx11.tar.gz"
