[[ViennaRNA]]
arch = "aarch64"
git-tree-sha1 = "69824ad32bfc8551dac855e033f7686a73fc7163"
os = "macos"

    [[ViennaRNA.download]]
    sha256 = "e9c33394092cbc453b0db9e506bfea83a6512d6ba8bc7d3e33fdc6fbd7e93770"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+0/ViennaRNA.v2.5.1.aarch64-apple-darwin.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8f6e35c59f18e67cebe5efeb50082412b12d2fbc"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "2b136286eec108a8186c9575061799adc7fde302d66b0399baf50a0c9ea50fe4"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+0/ViennaRNA.v2.5.1.aarch64-linux-gnu-cxx03.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3e953a7526a80cec25e5ff821de9fa3a0b68dd0"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "6b551c7b55a84520718031b1369cfb416b76ea47310e99cad27906eac4e5d034"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+0/ViennaRNA.v2.5.1.aarch64-linux-gnu-cxx11.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8973128110a3081459861bb530dccbeaabd1466f"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "13cd842fef40fd3ae027d37874e1a8d56c9c20c49fdfc06fc262e34edd99678b"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+0/ViennaRNA.v2.5.1.aarch64-linux-musl-cxx03.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f11735b46eb25765b4d8a691e1f4994272e27508"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "49cbac78e226fe45f1fc6aa9a2373270aed8d3a303c144ea26fddf5252f4b43b"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+0/ViennaRNA.v2.5.1.aarch64-linux-musl-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8abf6d1744af56a9789e3b466c4fa59673122bf9"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "2b6a7a9d9542a102a2f4053886d1c7aa7c6e4f40f6eb8492534e2439de898347"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+0/ViennaRNA.v2.5.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85466507d24852d6a0c0ed7c14c5c029fd49dc60"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "cd4bd30c8747d8d43ada5daed10aeeb8f2fdba530f42575af474802aa6b27dab"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+0/ViennaRNA.v2.5.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e96295c5846969b9a1636c666ac550ab1a4033ba"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "621189af63d49cd64fd20d933d8654fbfd03d3559bdb62179206e58fac254318"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+0/ViennaRNA.v2.5.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64dbf8ccef18f97c23ca8e903cb8bd64aa76d0b4"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "ff0fe0628bf590899400c2e91953314b35b98a06c589e6cb6486d16d1b00d523"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+0/ViennaRNA.v2.5.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb435bd7355cd718741b94766561237e1c146f99"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "0e88248d1f2e154a791618e901cf6e66f365421c1babceeb52bb7711f492c171"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+0/ViennaRNA.v2.5.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c91f2c8a3e5a0c6feb73eed60707114b01c52017"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "3e3410ceaf0c9c2f25642e1a5a57457962213544874d1ccdb6fa282aa1472bc7"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+0/ViennaRNA.v2.5.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "07d5c9252bc35bc2c466c0340ff9c3aa6b7a8a82"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "9896c9db1fcd1748396cc1956e4a2b75ccc3d895336e78e569c9857fe2ce094e"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+0/ViennaRNA.v2.5.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "776443c5e4f43b2e69186798d434d0cfdc1ed964"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "0a3ddd72bf720119374e79168072c0c330eafd06ea9311d30b998d42b1dbbfee"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+0/ViennaRNA.v2.5.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6060b6b1238de7ab4029e10d162c8a7d7b67c523"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "dd4eacf6159700b9166b395156a3d5db2f149d40c1bee57495628fbf9e201aa4"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+0/ViennaRNA.v2.5.1.i686-linux-gnu-cxx03.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ba4c6d2fa2e5a093cbefc8c0479b9673098161e"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "accafdaaec41570c13af4c21c727a762e0b8a65b0670ca3328f9f045245a2898"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+0/ViennaRNA.v2.5.1.i686-linux-gnu-cxx11.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7e216b7e78931164bdd6b67963bbea7ca9c8f4b7"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "35908ddb5dfeb3baa04f4ca8d51457d081b20e6b1ad0a157203eb1c2b36b9bc2"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+0/ViennaRNA.v2.5.1.i686-linux-musl-cxx03.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "999b8aa03fbb4141632bc4ef95c27b66f4052e0a"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "279adf6b0f4ae8e2fd4296f7664fc1a5e26735068710a1c09a17d96fa9bbc688"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+0/ViennaRNA.v2.5.1.i686-linux-musl-cxx11.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3436a687c71818d70454389ce477f6699f509b5f"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "1b24738fbefa30bb4e1d3152b83f8e263e416da81b119dde248f9da3c22a7c25"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+0/ViennaRNA.v2.5.1.i686-w64-mingw32-cxx03.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d160890d663c30841a0cc61553266637ff5a939d"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "e3ad22a44c5d159cf875cb114b75425164ddf66b673b5e5d0d4677a0b3536ff5"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+0/ViennaRNA.v2.5.1.i686-w64-mingw32-cxx11.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
git-tree-sha1 = "9deb449e042633bbbab931433c2f19071bfd5eb7"
os = "macos"

    [[ViennaRNA.download]]
    sha256 = "7da6c2b04b3202dcbde6c584c6fac4439d48d91058158183edd4b67d64e43dd8"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+0/ViennaRNA.v2.5.1.x86_64-apple-darwin.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7dc0f1755b0d88336f8fb7f4f148d511df1c463f"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "c8c290a953b2eb3dbee65298957d9bcc217223eba84f48b9b78743f1c4df99fe"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+0/ViennaRNA.v2.5.1.x86_64-linux-gnu-cxx03.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "205586a912d7d483be60bfe1af60d1f6762e14af"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "df37065ee21c2a4b965bd4d9abbbe798a553e8a4accf0ff18bd1946818d1a5ab"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+0/ViennaRNA.v2.5.1.x86_64-linux-gnu-cxx11.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d02775bb873bfcb1408324f76f4a176e5b820d40"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "464b1e870599ae1e8df1d16b14e34c6cfb7f26a880ca843b9612310ac07e477a"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+0/ViennaRNA.v2.5.1.x86_64-linux-musl-cxx03.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51c13f267df938d65761bdc4e3abc8083addea5f"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "fc0e4c523a4b7ab9385d586f94977b5b4714f2ea6b5604afc751c96dd2ca48a9"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+0/ViennaRNA.v2.5.1.x86_64-linux-musl-cxx11.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
git-tree-sha1 = "13def285cbaf8a40f0e40d3dfd4b086a1f371c1a"
os = "freebsd"

    [[ViennaRNA.download]]
    sha256 = "ebf35f6a6791adf8c23d72a22bf6eb42896182cbdc306553703a38aec76bece2"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+0/ViennaRNA.v2.5.1.x86_64-unknown-freebsd.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aaa9f37147ea41ee65e5df298db6b6c5833986f0"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "e57f9a441fc04b38247b502b504ee694912f17f8a92738a0fc2c669658f348e0"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+0/ViennaRNA.v2.5.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0cffa3a08bd35b8520179f8ef8aae086aff50534"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "0d29c39b7fc9aa0ddb547c95b7c0f30e6d73d239a09c703e6fe46040f0060c7b"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+0/ViennaRNA.v2.5.1.x86_64-w64-mingw32-cxx11.tar.gz"
