[[ViennaRNA]]
arch = "aarch64"
git-tree-sha1 = "4f98e288d845b6d4bf18302f120448c821b5aca0"
os = "macos"

    [[ViennaRNA.download]]
    sha256 = "557dad088dd6c20412e64f92b0c3bdd7e8b420544652190a4e38692d2b40ceea"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+2/ViennaRNA.v2.5.1.aarch64-apple-darwin.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "df1dba93ffc77962610e4d58400ebddae0227323"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "4b906e5fd7354c7c67b123b244aa10d6c88373d4d4697cfcc9e3d4b68ef7ae4b"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+2/ViennaRNA.v2.5.1.aarch64-linux-gnu-cxx03.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58f5c5c1b43d152faad7683de0cacd78cb85a5f4"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "b347564c1d7091e59bc04a0fc2fb8c07cac71f3011118393aed224862515c472"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+2/ViennaRNA.v2.5.1.aarch64-linux-gnu-cxx11.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb7ed666e3ece55d389aa395c370d0036ed83fb9"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "4ba6ded1ecaaaa4658f85973784031783e467243d888245d244793ea41ff3d87"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+2/ViennaRNA.v2.5.1.aarch64-linux-musl-cxx03.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11c2f6371066b8bbe9115506f8bd9deb3826470b"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "05b235e247f0f8b97fd4b39816d80e522e6bde060126794f921a671de70edb3c"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+2/ViennaRNA.v2.5.1.aarch64-linux-musl-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "610cc706fbc425e89a7055afb78ba972a186191b"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "a0f1bc01b0f74816475ab16e8af4517bb528bef536894ede0ac236e592e3b93c"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+2/ViennaRNA.v2.5.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6146ad722ebcdc9ca996d497d37a801d8034e103"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "99adefecd141774aaeb1731d64e3f3bb3996879ad78031a58f23f8733b69bb3b"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+2/ViennaRNA.v2.5.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4fd53bc363ef4e3884396907832f1b3ce8373e23"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "09befd2d9d3881be8df6cce43c2c0c93a9eab53e0a7053fa3ba09b04a63e23a2"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+2/ViennaRNA.v2.5.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "912104b91b9e3816761ef846ee41ae769ff667dd"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "c647850f8edbb57ac166e8f2eadad914e19c57d8d12dbfac2120c35e9b2b539e"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+2/ViennaRNA.v2.5.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "38eaeac5d0d75e15264148f102cb7017bc6f7f6e"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "6cb1e7529a5b58ac7f0ddeb39e9498db4e8034c18b6d72a9523298393ea2f30d"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+2/ViennaRNA.v2.5.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a0e8234768434267a74b6870e437a764b81c332"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "49f0fedf3c5cc2f9d18e5908061c92461dbb5b4a42ff135804b37908c1848f6d"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+2/ViennaRNA.v2.5.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eb74ce16bb71833a7c79e2d7ee75f0f3442e3ec6"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "b97990aff6a7bfb0fdebda7763fe3d2c7f299d172b4db0ccaa89d10d4750b388"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+2/ViennaRNA.v2.5.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a879575c758900e4f43b72710c3cfa6059576bfb"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "de76079caa38f5bee5f88c86d61bbe54b24fd7d5b1e2b75f3b1e61c64b0079c7"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+2/ViennaRNA.v2.5.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c59b109e0c8b7ddc823ef6bc733d8d18f6155502"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "b094d3f1f9facb82203b20190ddf444ba8bfd77e3ce87d4495a6aabe7405f064"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+2/ViennaRNA.v2.5.1.i686-linux-gnu-cxx03.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c24f4b9ee91800601ec4286e0688d42f52248dad"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "250be8444468668ec53c15bf237c14f5b6c035e9506d49d3ce8b92ae2d8cb5cf"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+2/ViennaRNA.v2.5.1.i686-linux-gnu-cxx11.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a20bd6b85ccb16538250f1a5faeb6225f5c1ea49"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "cffdee1cf21fd970009634e9294e5ba501a373d48e5230a0ebbb4c4f171e6e3a"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+2/ViennaRNA.v2.5.1.i686-linux-musl-cxx03.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2072d81ac6d849192c6b7fdab16d679848afd91"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "659f5416f9980aa71aacaffbf344947aa6f2d660afd968ce71b74f360870eb1d"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+2/ViennaRNA.v2.5.1.i686-linux-musl-cxx11.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c4846401b9088412c90734e918d83aba8f71cdab"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "b25552bf744f907a4d24fbd0e81af6b90689e322b1a055da85d5687d00609a07"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+2/ViennaRNA.v2.5.1.i686-w64-mingw32-cxx03.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d941759286154bef10b99ea0a5c4213d2095b3f"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "7d2b9359cbfd4db29f6be98a2153eda33372ff7b0b3cc57c95614b6bd2c55eff"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+2/ViennaRNA.v2.5.1.i686-w64-mingw32-cxx11.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
git-tree-sha1 = "0c96d0cbc90ea43f416e116c82d5b6fe89d283e1"
os = "macos"

    [[ViennaRNA.download]]
    sha256 = "ff991e9438515cf254cb7542b5d99225e364eea215a862cf484fd4c59fc40828"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+2/ViennaRNA.v2.5.1.x86_64-apple-darwin.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "551ac9602330802acd5f3d37e3a2370ee1074e48"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "9d925b8aecb7c1d15ea6d671da00b29739f8e0c6aa930264c12d5bccb6ab9507"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+2/ViennaRNA.v2.5.1.x86_64-linux-gnu-cxx03.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd97bc1285ab402975b87db60c480e1ee57a1853"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "bbeef75312982a001ec58ead8050dd1e18e006062865d3ebacadd664d752749c"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+2/ViennaRNA.v2.5.1.x86_64-linux-gnu-cxx11.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f054e7a507dd77e29522fcb8a0e66056dac46600"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "7decbe72a43b8a97c7be3da75e46b03cfa2b96b41310f4fb7eb9370676433bdb"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+2/ViennaRNA.v2.5.1.x86_64-linux-musl-cxx03.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7517b51a78faa3bc93bcf719ba864655b87a9594"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "cb46d244e1ad2ef638e563ccbf45c779c3b26dbf1c9dc9b04e521d30b29c39b1"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+2/ViennaRNA.v2.5.1.x86_64-linux-musl-cxx11.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
git-tree-sha1 = "20ff6fc69fc827114ff5a6a1ee14f70bb4c91ea3"
os = "freebsd"

    [[ViennaRNA.download]]
    sha256 = "8e709b5371eb1166d282336930ad39efc17a6bf2e24af6755dcd1f4b9c3d97b3"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+2/ViennaRNA.v2.5.1.x86_64-unknown-freebsd.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "decc25566a219fe35419166bceb04a66ab40c856"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "042c5d1a7b78112e266a6aa5db950edf1a215368383025503cf8a47444ceaf83"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+2/ViennaRNA.v2.5.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "624f23a5abf070903a8d2815dfc9660472c43c1f"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "054bfdf0d864856ff96023f8242d9d27143f575c60c1eff68fa1936ac27bf86e"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.5.1+2/ViennaRNA.v2.5.1.x86_64-w64-mingw32-cxx11.tar.gz"
