[[ViennaRNA]]
arch = "aarch64"
git-tree-sha1 = "8a2cdb7555a9c816962368767114147056d19029"
os = "macos"

    [[ViennaRNA.download]]
    sha256 = "d74202490aca3a017acf670d0d369bdbddfb98f52c1f9313fc529901929f0f3f"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.1+0/ViennaRNA.v2.6.1.aarch64-apple-darwin.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e687e5a7acd0286de0956745cd3b8aed7a158465"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "b932f6f38ac1c73ae6ea397e100da9a4aec02bd69ee2b81cbcb9d88a0e00c070"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.1+0/ViennaRNA.v2.6.1.aarch64-linux-gnu-cxx03.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2301a2c9acdfad927fe09c83a48cde2af440b56"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "263bed291b783cfdeb3e9698832b282142749f63d946f8d859456fe4756bbb82"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.1+0/ViennaRNA.v2.6.1.aarch64-linux-gnu-cxx11.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c5a0f2b5716bec7df39c1d622f6fc8c85b5c54f7"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "10447c5e9b83b280f5f8d6773af4c4b09003f60995514ea5059eb2b24cab480f"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.1+0/ViennaRNA.v2.6.1.aarch64-linux-musl-cxx03.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "793d4de1b60b69dcb0f74c772fa3bea625b476d2"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "2ca35675b6479e6402343010f2870e59188529206352e8ba72b14944830df836"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.1+0/ViennaRNA.v2.6.1.aarch64-linux-musl-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ee271971dbbcd319a5719708ccf1b3cd2fb2a31"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "68ceea07cef875f70d6c95522c5c80a47ec1bb1d47aef0a3d544809262e04677"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.1+0/ViennaRNA.v2.6.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0f52591c13089d21813684bff061e59945ba34dd"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "d6b56341e7e5ea9a43091f6f615e6c71f294303fb94fa43ced0b346868ebd0b6"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.1+0/ViennaRNA.v2.6.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5d32aaf27d31a1f9027121d705c9391796426e9f"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "7ebc90f0324695797f7f7fcc7caccbf14dcc435c7a2e9accba74540fe37b1767"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.1+0/ViennaRNA.v2.6.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "606edd8f1f9b9d94169932137d35619c01cf7457"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "acee2aba07bf211dd0ddd3bf79d1e56557ac2539c3ea5cb9a9dac61cc9a2a4ff"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.1+0/ViennaRNA.v2.6.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e2c8e8c693038aef3d38c0eafcb48d28f8173aa6"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "3c7ca2145b8e44332151d2862b567a65c92a5c0c5d3e1b9c63abde9aa2ac5c06"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.1+0/ViennaRNA.v2.6.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b908bd3dd9db66f78564f6a8168345ff4620c3c3"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "1f1c2f5f439ec9ed7f81fbdf4447174b27d0480f5254cdd8e2f0467efe49a82a"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.1+0/ViennaRNA.v2.6.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cf34ff1812ce15ac97589c583051cda0d34cea86"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "8689ec197295171deb12a42953d47e6128c1dbbec6a88a73a038ff6e3c711cfd"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.1+0/ViennaRNA.v2.6.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d172a7be380b7c6dfdff6a51d592cffab65dc37d"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "067efceb82312ea234a828c4d937ff3f74eb6205c6da665dd5444df6d7011764"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.1+0/ViennaRNA.v2.6.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "35b872e2172f5114f42e6019b39d52f35c8bda39"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "d6cec53538f01c0081640eae601a8414fe58a4ebf86efe3595a19f7606d29172"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.1+0/ViennaRNA.v2.6.1.i686-linux-gnu-cxx03.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5d983e35e1e57ff64ee052208803b709785459eb"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "37c6c967c1928e1e79c3c435d6f7d9ba738bb0b191a2e83f75c5c82066541b61"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.1+0/ViennaRNA.v2.6.1.i686-linux-gnu-cxx11.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "21b6cb4fe47a08c133918e769c476deb740157d8"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "5d1368da1ecdfbb0c2bbd5e5c25c16d4661b42d6028add0fdc59898cc0022506"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.1+0/ViennaRNA.v2.6.1.i686-linux-musl-cxx03.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ef72cd25b2444f05758aab330c256bc3c82870f"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "f6e0f000a4acaf72b2609fa65bb29529abd4f0da195d11f6dba053210c042fce"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.1+0/ViennaRNA.v2.6.1.i686-linux-musl-cxx11.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4e3f6df98b68616a0835b6f8709c530c20ff6d2c"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "90b4bfb9363474ed80d092487c7aaf4737c3d1b7f2b2aa7b79e4bda95869db9f"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.1+0/ViennaRNA.v2.6.1.i686-w64-mingw32-cxx03.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ce32b2afeb2e9a37663ee969c9ef0b78871d5a2"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "b6cd2b5710872c680bbe9b57b94e59ef9ae2b38f856abebc3253e100720775bc"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.1+0/ViennaRNA.v2.6.1.i686-w64-mingw32-cxx11.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
git-tree-sha1 = "75cc7ba3dd820874065c3ccc686f906253e99d90"
os = "macos"

    [[ViennaRNA.download]]
    sha256 = "873ec970c965a15e0113185fd832bc00e945b206dac78989c2ec68bcb78fd982"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.1+0/ViennaRNA.v2.6.1.x86_64-apple-darwin.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8c4809577e3c900e75f4d8f8539a9b6d452430e1"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "8c28b6e6bf7ab7c21592d659bdcf5331384ba21f689dd86042ce4e03176fd418"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.1+0/ViennaRNA.v2.6.1.x86_64-linux-gnu-cxx03.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4f64b22eafcc1fe3b215c2281aaff668f2420a7c"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "46b2a755377d24173642d29af75b517e7e54ca9742ee3a3409132ec97011c50e"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.1+0/ViennaRNA.v2.6.1.x86_64-linux-gnu-cxx11.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "70a74c95fcfb7821b162ca88646801aa7d820410"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "92bfcbbfd9b8931071acc2c1ce68252ade44bb6416def8e1c058afba51e2c872"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.1+0/ViennaRNA.v2.6.1.x86_64-linux-musl-cxx03.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3130edb1637c644ef28384f4e834567ac81eb24f"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "9e419c29bc56d807ce1cfb1f59df113d1fc81f8f1e329a54036315b060c15a09"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.1+0/ViennaRNA.v2.6.1.x86_64-linux-musl-cxx11.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
git-tree-sha1 = "ae2422e734e37ab4a4983007b30dd3e979d7d2b7"
os = "freebsd"

    [[ViennaRNA.download]]
    sha256 = "f87822ac0b7f05674a2a22f490b7f7c7fd0b9c56ff6d9a9fa5c5d1cf8738a59d"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.1+0/ViennaRNA.v2.6.1.x86_64-unknown-freebsd.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c644d304ee92627d6220b0fb667694b8d3b5dc5a"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "b432a983614b5491c873674bf2564b4d5cb96fa347410c20e83c226f3489f306"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.1+0/ViennaRNA.v2.6.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b50ba1fa47302e102d2e0f4813c12ee4d6d2361"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "1deac1084e137a6ec1ebd47c5f6c72a601d8d107d1f66015624c1fb3a261356d"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.1+0/ViennaRNA.v2.6.1.x86_64-w64-mingw32-cxx11.tar.gz"
