[[ViennaRNA]]
arch = "aarch64"
git-tree-sha1 = "5815303e9a0994122bb9001fcde35ddc2046215e"
os = "macos"

    [[ViennaRNA.download]]
    sha256 = "8983746c043cc0ea66d4cf3ec7ad94c2e15649f3b57de5ae0dc6bf76f1421ea4"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.0+0/ViennaRNA.v2.6.0.aarch64-apple-darwin.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d97c7c80603f2608fce3b6de96ffc3bd06049d5"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "526f1e67b0825d24ce825dc61dc299361a60021cca178f3174f46b2f00dd9ee5"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.0+0/ViennaRNA.v2.6.0.aarch64-linux-gnu-cxx03.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1fc2f53fadd47718eaf302c9836f090c7476233d"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "d6a7fcd6aa4fdc09b9ab1724e05944c7fb187312279ecc64bac70ce11b4a1ec2"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.0+0/ViennaRNA.v2.6.0.aarch64-linux-gnu-cxx11.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "61cc081b7eacc743f8897c68b07748c8c9110ffa"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "27abba1b1f40cbd0835e9749bdd9606122111df50a682b8dee676c72e0aa4976"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.0+0/ViennaRNA.v2.6.0.aarch64-linux-musl-cxx03.tar.gz"
[[ViennaRNA]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "66ab117d04faa98c5cf1b06e87c96aae73015b1b"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "44885e2f4d1c13d1fdb1d138f397db79ed76191fecd1c2e2f806d721d77dbaa8"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.0+0/ViennaRNA.v2.6.0.aarch64-linux-musl-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b77b3d5d6e00ce20a0da7cab5e80f563cf6dbb58"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "d5368ee09e3ce3dacbe5fd1041adc471ce040433988d2c6c6a8e6dff216ca381"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.0+0/ViennaRNA.v2.6.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39a16bd7b6df38771466088b0223433099483707"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "dd79ade3d61f610dff756e83a6b1c97c401b666eb7001e56ff8dfb46ea6eada3"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.0+0/ViennaRNA.v2.6.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4ff76df8ff2ff686f161bd9d58041934931962e3"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "1d9ebdfa6f34863df72c65988cd2acdae63df5774d997b905cbc640d0068b980"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.0+0/ViennaRNA.v2.6.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e7494b81e3facbd29c1137b29cbab43cf150a95"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "997902fa52d2001c6b15829a837a4fa1a102e66c567a6e09eee7f9ffccbeec42"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.0+0/ViennaRNA.v2.6.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bd8b1e447f92f1ae2590a9242645c93219baf89d"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "eb59a0c6a7e1200aaa1e369ca94eacaea7294abcde62ebf8688afbdff84bf8a8"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.0+0/ViennaRNA.v2.6.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e90a5b49acaa7541900d6ff52d374ec6d7b7d3f"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "a262742f904c01ca757a65a7a01ffffdc4029192756581ea7a2ad26f4383eef8"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.0+0/ViennaRNA.v2.6.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "790b7da592d25edacaab3138fe9221d1e228a333"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "b7b8e86867982d2c527ceff4964bdb1d2966a8b83e7f080afc6599a4bbfa63ab"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.0+0/ViennaRNA.v2.6.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ViennaRNA]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "809d1356026a1edd00ccaabaf044604574c1bc83"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "8063d929fa01a109f175b425b167a27c3d7c1d15373c6ab9e0660ad9a84d4cac"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.0+0/ViennaRNA.v2.6.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5ad4faa68bd572f5d007aacd8f932ffbed9db09b"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "f5f322d41f73590127612c95b80ec4080a33f765bca93e10de5c1e3500c04d04"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.0+0/ViennaRNA.v2.6.0.i686-linux-gnu-cxx03.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6172c73861db6ec7a80107889ba9ea53fb22e07b"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "3c770ec9ca83be3b61db1c90d0828167fbe29ecd5942c7908f5cf16b6a603bd8"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.0+0/ViennaRNA.v2.6.0.i686-linux-gnu-cxx11.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a7daa91552f086f47f37c4969abf35ecb875b228"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "ff6535aa988eb6cb503568077c913af9001c908b02eb78e0388698a1660b47bf"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.0+0/ViennaRNA.v2.6.0.i686-linux-musl-cxx03.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d223041f5c0237cb2b87f674970654207bbf8f2"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "c00f162acfa91a96efc189f710fea1ac310ed4392ec1ef2c75af9b115e96f04e"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.0+0/ViennaRNA.v2.6.0.i686-linux-musl-cxx11.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5cf819fb2d606de1180d2942d7ae3c628dd483b1"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "290f65ff63b031053a8210a2857eab9738f72d773fcd7a1c26423ad924663acd"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.0+0/ViennaRNA.v2.6.0.i686-w64-mingw32-cxx03.tar.gz"
[[ViennaRNA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "459e6fde89a57b10b959773c92ccb1b7255ea5c9"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "4f863ce9a837a0239711fdd16cff0b8cbfe5f470f8747e59df440d4e5e73f652"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.0+0/ViennaRNA.v2.6.0.i686-w64-mingw32-cxx11.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
git-tree-sha1 = "8b835c2dbb32847d48717d13368c02f6f23a31cb"
os = "macos"

    [[ViennaRNA.download]]
    sha256 = "c348219dc6e9f3f42c52bde921e8f0930c0ef96dedcf64befeec01538c204acd"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.0+0/ViennaRNA.v2.6.0.x86_64-apple-darwin.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "11a9f759acae5151cb73aa4d3fe7ca0327752c24"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "921206516903bae9b9c545ecb964868ff61c0bdfa5dedbb17034019919b618a6"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.0+0/ViennaRNA.v2.6.0.x86_64-linux-gnu-cxx03.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d1a0e2da7e980aa35ca19b4b362086fe05e7316f"
libc = "glibc"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "3051fb54d7afd95af0e0659bd013f53a66e43c18315c4c346fb0fc02f8604dba"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.0+0/ViennaRNA.v2.6.0.x86_64-linux-gnu-cxx11.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c9b7d5a95e39bab78e605adc265d1adc1a35a161"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "d19e7e5ea3d14537e5b7144a38ea317662c40f6bbafa8c7877dc72190205c4a6"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.0+0/ViennaRNA.v2.6.0.x86_64-linux-musl-cxx03.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c572bb1aea58a9f2b82f5c72a71a6a3bd529625"
libc = "musl"
os = "linux"

    [[ViennaRNA.download]]
    sha256 = "9885fb62e3d70ca37fefd12e999fc6ee3666331d63a09f419324c8c8fc4d4d23"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.0+0/ViennaRNA.v2.6.0.x86_64-linux-musl-cxx11.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
git-tree-sha1 = "3f892dad2695083911884e863c29901b594c5577"
os = "freebsd"

    [[ViennaRNA.download]]
    sha256 = "ab24ee34cb0ab10fb3bb063ca08bf72ae4cd3cc55525699d4c0182f690a9d0da"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.0+0/ViennaRNA.v2.6.0.x86_64-unknown-freebsd.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8fbaf3b53ea2d22b8d6fa3c113bfb0ae822907ce"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "bbfbc687f033e777f797f87da5fed54ed7bc6872f48d406bb2b7fc57821153e9"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.0+0/ViennaRNA.v2.6.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[ViennaRNA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef97234b77ec8473024d4315d169879c106a2da8"
os = "windows"

    [[ViennaRNA.download]]
    sha256 = "87e80dd9b4ab054a9bd09f7e2ed054cee37d3f45bb150d6e6e197017a7e0429a"
    url = "https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl/releases/download/ViennaRNA-v2.6.0+0/ViennaRNA.v2.6.0.x86_64-w64-mingw32-cxx11.tar.gz"
