# Autogenerated wrapper script for ViennaRNA_jll for i686-w64-mingw32-cxx11
export AnalyseDists, AnalyseSeqs, Kinfold, Kinfold, RNA2Dfold, RNALalifold, RNALfold, RNAPKplex, RNAaliduplex, RNAalifold, RNAcofold, RNAdistance, RNAdos, RNAduplex, RNAeval, RNAfold, RNAforester, RNAheat, RNAinverse, RNAlocmin, RNAmultifold, RNApaln, RNAparconv, RNApdist, RNAplex, RNAplfold, RNAplot, RNApvmin, RNAsnoop, RNAsubopt, RNAup, b2ct, ct2db, libRNA, popt

using MPFR_jll
using GSL_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("ViennaRNA")
JLLWrappers.@declare_library_product(libRNA, "libRNA.dll")
JLLWrappers.@declare_executable_product(AnalyseDists)
JLLWrappers.@declare_executable_product(AnalyseSeqs)
JLLWrappers.@declare_executable_product(Kinfold)
JLLWrappers.@declare_executable_product(Kinfold)
JLLWrappers.@declare_executable_product(RNA2Dfold)
JLLWrappers.@declare_executable_product(RNALalifold)
JLLWrappers.@declare_executable_product(RNALfold)
JLLWrappers.@declare_executable_product(RNAPKplex)
JLLWrappers.@declare_executable_product(RNAaliduplex)
JLLWrappers.@declare_executable_product(RNAalifold)
JLLWrappers.@declare_executable_product(RNAcofold)
JLLWrappers.@declare_executable_product(RNAdistance)
JLLWrappers.@declare_executable_product(RNAdos)
JLLWrappers.@declare_executable_product(RNAduplex)
JLLWrappers.@declare_executable_product(RNAeval)
JLLWrappers.@declare_executable_product(RNAfold)
JLLWrappers.@declare_executable_product(RNAforester)
JLLWrappers.@declare_executable_product(RNAheat)
JLLWrappers.@declare_executable_product(RNAinverse)
JLLWrappers.@declare_executable_product(RNAlocmin)
JLLWrappers.@declare_executable_product(RNAmultifold)
JLLWrappers.@declare_executable_product(RNApaln)
JLLWrappers.@declare_executable_product(RNAparconv)
JLLWrappers.@declare_executable_product(RNApdist)
JLLWrappers.@declare_executable_product(RNAplex)
JLLWrappers.@declare_executable_product(RNAplfold)
JLLWrappers.@declare_executable_product(RNAplot)
JLLWrappers.@declare_executable_product(RNApvmin)
JLLWrappers.@declare_executable_product(RNAsnoop)
JLLWrappers.@declare_executable_product(RNAsubopt)
JLLWrappers.@declare_executable_product(RNAup)
JLLWrappers.@declare_executable_product(b2ct)
JLLWrappers.@declare_executable_product(ct2db)
JLLWrappers.@declare_executable_product(popt)
function __init__()
    JLLWrappers.@generate_init_header(MPFR_jll, GSL_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libRNA,
        "bin\\libRNA.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        AnalyseDists,
        "bin\\AnalyseDists.exe",
    )

    JLLWrappers.@init_executable_product(
        AnalyseSeqs,
        "bin\\AnalyseSeqs.exe",
    )

    JLLWrappers.@init_executable_product(
        Kinfold,
        "bin\\Kinfold.exe",
    )

    JLLWrappers.@init_executable_product(
        Kinfold,
        "bin\\kinwalker.exe",
    )

    JLLWrappers.@init_executable_product(
        RNA2Dfold,
        "bin\\RNA2Dfold.exe",
    )

    JLLWrappers.@init_executable_product(
        RNALalifold,
        "bin\\RNALalifold.exe",
    )

    JLLWrappers.@init_executable_product(
        RNALfold,
        "bin\\RNALfold.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAPKplex,
        "bin\\RNAPKplex.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAaliduplex,
        "bin\\RNAaliduplex.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAalifold,
        "bin\\RNAalifold.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAcofold,
        "bin\\RNAcofold.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAdistance,
        "bin\\RNAdistance.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAdos,
        "bin\\RNAdos.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAduplex,
        "bin\\RNAduplex.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAeval,
        "bin\\RNAeval.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAfold,
        "bin\\RNAfold.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAforester,
        "bin\\RNAforester.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAheat,
        "bin\\RNAheat.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAinverse,
        "bin\\RNAinverse.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAlocmin,
        "bin\\RNAlocmin.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAmultifold,
        "bin\\RNAmultifold.exe",
    )

    JLLWrappers.@init_executable_product(
        RNApaln,
        "bin\\RNApaln.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAparconv,
        "bin\\RNAparconv.exe",
    )

    JLLWrappers.@init_executable_product(
        RNApdist,
        "bin\\RNApdist.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAplex,
        "bin\\RNAplex.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAplfold,
        "bin\\RNAplfold.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAplot,
        "bin\\RNAplot.exe",
    )

    JLLWrappers.@init_executable_product(
        RNApvmin,
        "bin\\RNApvmin.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAsnoop,
        "bin\\RNAsnoop.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAsubopt,
        "bin\\RNAsubopt.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAup,
        "bin\\RNAup.exe",
    )

    JLLWrappers.@init_executable_product(
        b2ct,
        "bin\\b2ct.exe",
    )

    JLLWrappers.@init_executable_product(
        ct2db,
        "bin\\ct2db.exe",
    )

    JLLWrappers.@init_executable_product(
        popt,
        "bin\\popt.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
