# Autogenerated wrapper script for ViennaRNA_jll for x86_64-unknown-freebsd
export AnalyseDists, AnalyseSeqs, Kinfold, RNA2Dfold, RNALalifold, RNALfold, RNAPKplex, RNAaliduplex, RNAalifold, RNAcofold, RNAdistance, RNAdos, RNAduplex, RNAeval, RNAfold, RNAforester, RNAheat, RNAinverse, RNAlocmin, RNAmultifold, RNApaln, RNAparconv, RNApdist, RNAplex, RNAplfold, RNAplot, RNApvmin, RNAsnoop, RNAsubopt, RNAup, RNAxplorer, b2ct, ct2db, kinwalker, libRNA, popt

using MPFR_jll
using GSL_jll
using LLVMOpenMP_jll
using OpenBLAS32_jll
JLLWrappers.@generate_wrapper_header("ViennaRNA")
JLLWrappers.@declare_library_product(libRNA, "libRNA.so")
JLLWrappers.@declare_executable_product(AnalyseDists)
JLLWrappers.@declare_executable_product(AnalyseSeqs)
JLLWrappers.@declare_executable_product(Kinfold)
JLLWrappers.@declare_executable_product(RNA2Dfold)
JLLWrappers.@declare_executable_product(RNALalifold)
JLLWrappers.@declare_executable_product(RNALfold)
JLLWrappers.@declare_executable_product(RNAPKplex)
JLLWrappers.@declare_executable_product(RNAaliduplex)
JLLWrappers.@declare_executable_product(RNAalifold)
JLLWrappers.@declare_executable_product(RNAcofold)
JLLWrappers.@declare_executable_product(RNAdistance)
JLLWrappers.@declare_executable_product(RNAdos)
JLLWrappers.@declare_executable_product(RNAduplex)
JLLWrappers.@declare_executable_product(RNAeval)
JLLWrappers.@declare_executable_product(RNAfold)
JLLWrappers.@declare_executable_product(RNAforester)
JLLWrappers.@declare_executable_product(RNAheat)
JLLWrappers.@declare_executable_product(RNAinverse)
JLLWrappers.@declare_executable_product(RNAlocmin)
JLLWrappers.@declare_executable_product(RNAmultifold)
JLLWrappers.@declare_executable_product(RNApaln)
JLLWrappers.@declare_executable_product(RNAparconv)
JLLWrappers.@declare_executable_product(RNApdist)
JLLWrappers.@declare_executable_product(RNAplex)
JLLWrappers.@declare_executable_product(RNAplfold)
JLLWrappers.@declare_executable_product(RNAplot)
JLLWrappers.@declare_executable_product(RNApvmin)
JLLWrappers.@declare_executable_product(RNAsnoop)
JLLWrappers.@declare_executable_product(RNAsubopt)
JLLWrappers.@declare_executable_product(RNAup)
JLLWrappers.@declare_executable_product(RNAxplorer)
JLLWrappers.@declare_executable_product(b2ct)
JLLWrappers.@declare_executable_product(ct2db)
JLLWrappers.@declare_executable_product(kinwalker)
JLLWrappers.@declare_executable_product(popt)
function __init__()
    JLLWrappers.@generate_init_header(MPFR_jll, GSL_jll, LLVMOpenMP_jll, OpenBLAS32_jll)
    JLLWrappers.@init_library_product(
        libRNA,
        "lib/libRNA.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        AnalyseDists,
        "bin/AnalyseDists",
    )

    JLLWrappers.@init_executable_product(
        AnalyseSeqs,
        "bin/AnalyseSeqs",
    )

    JLLWrappers.@init_executable_product(
        Kinfold,
        "bin/Kinfold",
    )

    JLLWrappers.@init_executable_product(
        RNA2Dfold,
        "bin/RNA2Dfold",
    )

    JLLWrappers.@init_executable_product(
        RNALalifold,
        "bin/RNALalifold",
    )

    JLLWrappers.@init_executable_product(
        RNALfold,
        "bin/RNALfold",
    )

    JLLWrappers.@init_executable_product(
        RNAPKplex,
        "bin/RNAPKplex",
    )

    JLLWrappers.@init_executable_product(
        RNAaliduplex,
        "bin/RNAaliduplex",
    )

    JLLWrappers.@init_executable_product(
        RNAalifold,
        "bin/RNAalifold",
    )

    JLLWrappers.@init_executable_product(
        RNAcofold,
        "bin/RNAcofold",
    )

    JLLWrappers.@init_executable_product(
        RNAdistance,
        "bin/RNAdistance",
    )

    JLLWrappers.@init_executable_product(
        RNAdos,
        "bin/RNAdos",
    )

    JLLWrappers.@init_executable_product(
        RNAduplex,
        "bin/RNAduplex",
    )

    JLLWrappers.@init_executable_product(
        RNAeval,
        "bin/RNAeval",
    )

    JLLWrappers.@init_executable_product(
        RNAfold,
        "bin/RNAfold",
    )

    JLLWrappers.@init_executable_product(
        RNAforester,
        "bin/RNAforester",
    )

    JLLWrappers.@init_executable_product(
        RNAheat,
        "bin/RNAheat",
    )

    JLLWrappers.@init_executable_product(
        RNAinverse,
        "bin/RNAinverse",
    )

    JLLWrappers.@init_executable_product(
        RNAlocmin,
        "bin/RNAlocmin",
    )

    JLLWrappers.@init_executable_product(
        RNAmultifold,
        "bin/RNAmultifold",
    )

    JLLWrappers.@init_executable_product(
        RNApaln,
        "bin/RNApaln",
    )

    JLLWrappers.@init_executable_product(
        RNAparconv,
        "bin/RNAparconv",
    )

    JLLWrappers.@init_executable_product(
        RNApdist,
        "bin/RNApdist",
    )

    JLLWrappers.@init_executable_product(
        RNAplex,
        "bin/RNAplex",
    )

    JLLWrappers.@init_executable_product(
        RNAplfold,
        "bin/RNAplfold",
    )

    JLLWrappers.@init_executable_product(
        RNAplot,
        "bin/RNAplot",
    )

    JLLWrappers.@init_executable_product(
        RNApvmin,
        "bin/RNApvmin",
    )

    JLLWrappers.@init_executable_product(
        RNAsnoop,
        "bin/RNAsnoop",
    )

    JLLWrappers.@init_executable_product(
        RNAsubopt,
        "bin/RNAsubopt",
    )

    JLLWrappers.@init_executable_product(
        RNAup,
        "bin/RNAup",
    )

    JLLWrappers.@init_executable_product(
        RNAxplorer,
        "bin/RNAxplorer",
    )

    JLLWrappers.@init_executable_product(
        b2ct,
        "bin/b2ct",
    )

    JLLWrappers.@init_executable_product(
        ct2db,
        "bin/ct2db",
    )

    JLLWrappers.@init_executable_product(
        kinwalker,
        "bin/kinwalker",
    )

    JLLWrappers.@init_executable_product(
        popt,
        "bin/popt",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
