# Autogenerated wrapper script for ViennaRNA_jll for x86_64-w64-mingw32
export AnalyseDists, AnalyseSeqs, RNALfold, RNAaliduplex, RNAalifold, RNAcofold, RNAdistance, RNAduplex, RNAeval, RNAfold, RNAheat, RNAinverse, RNApaln, RNApdist, RNAplfold, RNAplot, RNAsubopt, RNAup, libRNA

JLLWrappers.@generate_wrapper_header("ViennaRNA")
JLLWrappers.@declare_library_product(libRNA, "libRNA.dll")
JLLWrappers.@declare_executable_product(AnalyseDists)
JLLWrappers.@declare_executable_product(AnalyseSeqs)
JLLWrappers.@declare_executable_product(RNALfold)
JLLWrappers.@declare_executable_product(RNAaliduplex)
JLLWrappers.@declare_executable_product(RNAalifold)
JLLWrappers.@declare_executable_product(RNAcofold)
JLLWrappers.@declare_executable_product(RNAdistance)
JLLWrappers.@declare_executable_product(RNAduplex)
JLLWrappers.@declare_executable_product(RNAeval)
JLLWrappers.@declare_executable_product(RNAfold)
JLLWrappers.@declare_executable_product(RNAheat)
JLLWrappers.@declare_executable_product(RNAinverse)
JLLWrappers.@declare_executable_product(RNApaln)
JLLWrappers.@declare_executable_product(RNApdist)
JLLWrappers.@declare_executable_product(RNAplfold)
JLLWrappers.@declare_executable_product(RNAplot)
JLLWrappers.@declare_executable_product(RNAsubopt)
JLLWrappers.@declare_executable_product(RNAup)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libRNA,
        "bin\\libRNA.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        AnalyseDists,
        "bin\\AnalyseDists.exe",
    )

    JLLWrappers.@init_executable_product(
        AnalyseSeqs,
        "bin\\AnalyseSeqs.exe",
    )

    JLLWrappers.@init_executable_product(
        RNALfold,
        "bin\\RNALfold.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAaliduplex,
        "bin\\RNAaliduplex.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAalifold,
        "bin\\RNAalifold.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAcofold,
        "bin\\RNAcofold.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAdistance,
        "bin\\RNAdistance.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAduplex,
        "bin\\RNAduplex.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAeval,
        "bin\\RNAeval.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAfold,
        "bin\\RNAfold.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAheat,
        "bin\\RNAheat.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAinverse,
        "bin\\RNAinverse.exe",
    )

    JLLWrappers.@init_executable_product(
        RNApaln,
        "bin\\RNApaln.exe",
    )

    JLLWrappers.@init_executable_product(
        RNApdist,
        "bin\\RNApdist.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAplfold,
        "bin\\RNAplfold.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAplot,
        "bin\\RNAplot.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAsubopt,
        "bin\\RNAsubopt.exe",
    )

    JLLWrappers.@init_executable_product(
        RNAup,
        "bin\\RNAup.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
